### ISSUE TITLE
Circular Dataclasses Not Converted Correctly

### ISSUE THREAD

**Issue by BennoCrafter** [BennoCrafter/YAML2Dataclass#1]
```yaml
myself:
  name: Benno
  age: 30
  friends:
    - name: John
      age: 20
      friends:
        - name: Jane
          age: 21
          friends: []

    - name: Alice
      age: 22
      friends: []
```
If using this yaml example it returns a list of dicts for friends
